### ISSUE TITLE
Add dependencies for Mocha and Chai so that we can write tests

### ISSUE THREAD

**Issue by jordanhatcher** [jordanhatcher/cookery#1]
Mocha: https://mochajs.org/
Chai: https://www.chaijs.com/

**Comment by gmelodie** [comment]
Can I tackle this? I'm new to javascript and npm, could you give me some material about dependency management?

**Comment by lyonsbp** [comment]
@LTKills you will want to look into `npm install` and install both deps, then you will need to import the modules into the project.

**Comment by jordanhatcher** [comment]
@LTKills sure, that would be great if you want to take on this issue! Like @lyonsbp mentioned, you can look at `npm install` and how to use it. If you have any more questions just leave a comment!

**Comment by haidarrifki** [comment]
i take this :sweat_smile:

**Comment by gmelodie** [comment]
I believe #9 should not be accepted, there was no previous discussion whatsoever. Anyways, I'm still up for it if you want @jordanhatcher

**Comment by jordanhatcher** [comment]
@LTKills yes if you would still like to work on this, I'll merge your pull request. @haidarrifki thank you for spending the time to contribute, but I will close #9 in order to let @LTKills  work on this.

**Comment by gmelodie** [comment]
As these dependencies are for testing, I added them as dev dependencies. Now should I import them into the code as well (if yes, how exactly?) or you are just looking for lock file updating?

**Comment by jordanhatcher** [comment]
This task is just for updating the package.json and package-lock.json. It sounds like what you have is great!

**Comment by jordanhatcher** [comment]
Closed in #12
