### ISSUE TITLE
Don't validate array lengths in Joi ORF schema

### ISSUE THREAD

**Issue by jordanhatcher** [jordanhatcher/cookery#2]
Instead of having `.min(1)` in the Joi schema (`src/openrecipe.js`) for some lists, it might be better to only render those lists if they have elements. Remove `.min(1)` from the schema validation, and update the template file to render empty lists properly.

**Comment by harshalitalele** [comment]
I would take up this issue.

**Comment by jordanhatcher** [comment]
@harshalitalele That would be great! Let me know if you have any questions.

**Comment by harshalitalele** [comment]
While trying to run the application I faced following issues:

1. There is no 'tmp/tempCookbook.html' in examples folder.
2. After adding that, pdf.js is returning rejection as "Error: navigation error" for cookery --name MyExampleCookbook command.

I am trying to figure out cause of navigation error right now.

Can you guess why would I be getting that?

**Comment by harshalitalele** [comment]
Ok, I got it.
I had to change the tempHtmlFile path to make it take the relative path initially, which it was taking it as absolute path while generating pdf.

**Comment by jordanhatcher** [comment]
Closed in #11
