### ISSUE TITLE
Change file name and extension for template file

### ISSUE THREAD

**Issue by jordanhatcher** [jordanhatcher/cookery#4]
Currently, the template file is called `recipe.tpl`. Preferred name would be `cookbook.mustache`.

**Comment by b-dashyan** [comment]
Hey man, so you need me to change the filename to `cookbook.mustache` and update the import statement in `openrecipe.js`? Anything else?

**Comment by jthodge** [comment]
My apologies @bagshik!
I completed this and submitted #5 before I saw your comment.

**Comment by b-dashyan** [comment]
No worries @jthodge, good job 👌
