### ISSUE TITLE
Add a license file to the project

### ISSUE THREAD

**Issue by jordanhatcher** [jordanhatcher/cookery#6]
**Attention** 
I am specifically creating this issue for someone who wants to work on their very first pull request (ever) **only**! If you create a pull request for this issue and it is not your first pull request, I will mark it as spam!

For this issue, add a file called `LICENSE` containing the CC0 license file. This file can be found [here](https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt). It just needs to be renamed to `LICENSE`, and added to this repo!

If you would like to work on this issue, just comment on this issue. In order to be fair, I will let the first person to comment be the one to work on the issue, so please check to see if someone has already claimed this issue before getting started!

**Comment by kiminohero** [comment]
sir I would like to work on this issue

**Comment by kiminohero** [comment]
i would like to work on this

**Comment by arojunior** [comment]
Can I take this one? You mean... first pul request in this repository or first ever?

**Comment by jordanhatcher** [comment]
Hi @arojunior , I mean first pull request ever. I will update the issue to be more clear! Sorry, but I'll get someone else to work on this as I see you've made pull requests before.

**Comment by berkaybarlas** [comment]
I can do it :D

**Comment by jordanhatcher** [comment]
Closed in #10
